apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PolaganiRavikumar/gitops.git
    targetRevision: main
    path: charts/cert-manager
    helm:
      valueFiles:
        - ../../overrides/cert-manager.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
