apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PolaganiRavikumar/gitops-course.git
    targetRevision: main
    path: charts/traefik
    helm:
      valueFiles:
        - ../../overrides/traefik.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
